id: P007028
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5468
  title: སྔོན་འགྲོའི་དཔེ་རིས་རབ་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    844a799e493b4c78b5472e20e8af07bb:
      image_group_id: I3CN5470
      title: ''
      volume_number: 1
      total_pages: 290
    4db39fe14bc34910ae351ffdae9cf66b:
      image_group_id: I3CN5471
      title: ''
      volume_number: 2
      total_pages: 122
ebook_metadata:
  title: སྔོན་འགྲོའི་དཔེ་རིས་རབ་གསལ་མེ་ལོང་།
  author: ''
  sku: P007028
  cover: cover.jpg
  layers:
  - pagination
