id: I9952B4B6
legacy_id: P007028
ocr_import_info:
  bdrc_scan_id: W3CN5468
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:39:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:10:07.714496+00:00'
last_modified: 2022-09-03 23:10:18.625485
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5468
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5468
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔོན་འགྲོའི་དཔེ་རིས་རབ་གསལ་མེ་ལོང་།
statistics:
  ocr_word_mean_confidence_index: 0.8618275981380726
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN5470:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5470
      total_pages: 290
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5470.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8684418930445795
    legacy_id: v001
  I3CN5471:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5471
      total_pages: 122
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN5471.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8506553818961394
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
