id: I9952B4B6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:40:18+00:00'
last_modified: '2022-06-08T13:21:52.142090+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5468
  title: སྔོན་འགྲོའི་དཔེ་རིས་རབ་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CB5B:
      image_group_id: I3CN5470
      title: Volume 1 of sngon 'gro'i dpe ris rab gsal me long /
      total_pages: 290
      order: 1
      base_file: CB5B.txt
    02CA:
      image_group_id: I3CN5471
      title: Volume 2 of sngon 'gro'i dpe ris rab gsal me long /
      total_pages: 122
      order: 2
      base_file: 02CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
